# Generated by Django 4.2.11 on 2026-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
